kind: PersistentVolume
apiVersion: v1
metadata:
  name: alluxio-journal-volume-0
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/alluxio-journal-0
